version: "3.9"
services:
  service-reapprovisionnement:
    container_name: service-reappro
    image: ghcr.io/laurich-app/service-reapprovisionnement:1.1.1
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-reappro:27017/
      - MONGO_DATABASE=reappro
      - RABBIT_HOST=rabbit

  mongo-reappro:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  client:
    container_name: client-microservice
    build: .
    volumes:
      - ./app/:/app/
    tty: true
    stdin_open: true
    ports:
      - 4200:4200

  service-passerelle:
    image: ghcr.io/laurich-app/service-passerelle:1.1.0
    ports:
      - 8080:8080
    environment:
      - CLIENT_URL=http://client
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500

  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:0.0.3
    ports:
      - 8888:8888

  postgres:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:1.2.1
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
      - RABBIT_HOST=rabbit
    depends_on:
      - serveur-conf
      - discovery

  postgres-catalogue:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-catalogue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-catalogue:
    image: ghcr.io/laurich-app/service-produits:1.2.1
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - POSTGRES_URL=jdbc:postgresql://postgres-catalogue:5432/service-catalogue
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
      - RABBIT_HOST=rabbit
    depends_on:
      - serveur-conf
      - discovery
      - postgres-catalogue

  service-commande:
    image: ghcr.io/laurich-app/service-commandes:1.1.2
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-commande:27017/
      - MONGO_DATABASE=commande
      - RABBIT_HOST=rabbit
    depends_on:
      - serveur-conf
      - discovery
      - mongo-commande

  mongo-commande:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  rabbit:
    image: rabbitmq:3.12.13-management
