FROM node:20.11.0 as builder

RUN npm install -g @angular/cli

WORKDIR /app/

# Copier les fichiers de package.json et package-lock.json
COPY ./app/package.json /app/

RUN npm install

# Copier le code source de l'application
COPY ./app/ /app/

# Construire l'application Angular pour la production
RUN ng build

# Étape 2 : Utiliser un serveur HTTP léger pour servir l'application
FROM nginx:alpine

# Copier les fichiers construits de l'étape précédente vers le répertoire de travail de Nginx
COPY --from=builder /app/dist/app/browser/ /usr/share/nginx/html/

# Gestion des URLs (/ /*)
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY ./scripts/ /scripts/

RUN apk upgrade && apk add dos2unix findutils

RUN find scripts -type f -exec dos2unix {} \;
RUN chmod a+x /scripts/*

# Start the Nginx service
CMD ["/scripts/start-app.sh", "/usr/share/nginx/html"]