version: "3.9"
services:
  service-reapprovisionnement:
    container_name: service-reappro
    image: ghcr.io/laurich-app/service-reapprovisionnement:1.0.2
    environment:
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-reappro:27017/
      - MONGO_DATABASE=reappro

  mongo-reappro:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  client:
    container_name: client-microservice
    build: .
    volumes:
      - ./app/:/app/
    tty: true
    stdin_open: true
    ports:
      - 4200:4200

  service-passerelle:
    image: ghcr.io/laurich-app/service-passerelle:1.1.0
    ports:
      - 8080:8080
    environment:
      - CLIENT_URL=http://client
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500

  discovery:
    image: consul:1.15
    ports:
      - 8500:8500

  serveur-conf:
    image: ghcr.io/laurich-app/serveur-conf:0.0.3
    ports:
      - 8888:8888

  postgres:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-utilisateur:
    image: ghcr.io/laurich-app/service-utilisateur:1.1.0
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - PRIVATE_KEY=app_pkcs8.prv
      - PUBLIC_KEY=app.pub
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/service-utilisateur
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
    depends_on:
      - serveur-conf
      - discovery

  postgres-catalogue:
    image: postgres:12.17
    environment:
      - POSTGRES_DB=service-catalogue
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pswd

  service-catalogue:
    image: ghcr.io/laurich-app/service-produits:1.0.3
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - POSTGRES_URL=jdbc:postgresql://postgres-catalogue:5432/service-catalogue
      - POSTGRES_USER=user
      - POSTGRES_PSWD=pswd
    depends_on:
      - serveur-conf
      - discovery
      - postgres-catalogue

  service-commande:
    image: ghcr.io/laurich-app/service-commandes:1.0.4
    environment:
      - URL_CONFIG_SERVEUR=http://serveur-conf:8888
      - CONSUL_HOST=discovery
      - CONSUL_PORT=8500
      - MONGO_URL=mongodb://user:pswd@mongo-commande:27017/
      - MONGO_DATABASE=commande
    depends_on:
      - serveur-conf
      - discovery
      - mongo-commande

  mongo-commande:
    image: mongo:7.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pswd

  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pswd
      ME_CONFIG_MONGODB_URL: mongodb://user:pswd@mongo-commande:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo-commande
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
