export enum NotificationFonctionEnum {
  NOTIFIER_ADMIN_COMMANDE = 'NOTIFIER_ADMIN_COMMANDE',
  NOTIFIER_USER_COMMANDE = 'NOTIFIER_USER_COMMANDE',
  NOTIFIER_USER_INSCRIPTION = 'NOTIFIER_USER_INSCRIPTION',
}
